POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "poco x3 pro",
  "price": "209",
  "image": "example.com/image2"
}

### 

GET http://localhost:5000/api/products

### 

DELETE http://localhost:5000/api/products/6986912af7e76a2a4e41aa46

###

PUT http://localhost:5000/api/products/698690c7f7e76a2a4e41aacc
Content-Type: application/json

{
  "name": "greenphone updated",
  "price": "3500",
  "image": "example.com/image2-updated"
}