POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "poco x3 pro",
  "price": "209",
  "image": "example.com/image2"
}

### 

GET http://localhost:5000/api/products

### 

DELETE http://localhost:5000/api/products/69876d7f6bb9a2976c66b4ef

###

PUT http://localhost:5000/api/products/69876d986bb9a2976c66b4f1
Content-Type: application/json

{
  "name": "greenphone updated",
  "price": "3500",
  "image": "example.com/image2-updated"
}